import = ["/home/murtaza/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "SemiLight"

[window]
opacity = 0.85
decorations = "None"

[keyboard]
bindings = [
	{ key = "L", mods = "Super", chars = "\u0000\t"},
	{ key = "H", mods = "Super", chars = "\u0000\u001b[Z"},
	{ key = "T", mods = "Super", chars = "\u0000c"},
]

