import = ["/home/murtaza/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 14.0

[font.normal]
family = "UbuntuMono Nerd Font"
style = "SemiLight"
