#! /bin/bash
# set -e -o pipefail
cat > /dev/null
echo "Log in with bitwarden:" > /dev/tty
while [ -z "$item" ]; do
	item=$(bw get item 740b637e-59d8-4f84-901e-b0180122501b < /dev/tty)
	code=$?
	if [ -z "$item" ]; then
		# when bw is canceled with ^C it returns 0
		if [ $code = 0 ]; then
			echo "[cancelled]" > /dev/tty
			exit 1
		fi
		echo "Retry..." > /dev/tty
	fi
done
echo $item | jq .notes -r | xargs printf "password=%s\n"

